export const exerciseOptions = [
    { value: 'Squat' },
    { value: 'Bench Press' },
    { value: 'Deadlift' },
    { value: 'Overhead Press' },
    { value: 'Alternating Dumbbell Curl' },
    { value: 'Barbell Curl' },
    { value: 'Barbell Glute Bridge' },
    { value: 'Barbell Lunge' },
    { value: 'Barbell Reverse Lunge' },
    { value: 'Barbell Shrug' },
    { value: 'Barbell Split Squat' },
    { value: 'Barbell Box Squat' },
    { value: 'Bent Over Row' },
    { value: 'Close Grip Bench Press' },
    { value: 'Concentration Curl' },
    { value: 'Decline Bench Press' },
    { value: 'Dumbbell Bicep Curl' },
    { value: 'Dumbbell Bulgarian Split Squat' },
    { value: 'Dumbbell Deadlift' },
    { value: 'Dumbbell Floor Press' },
    { value: 'Dumbbell Fly' },
    { value: 'Dumbbell Front Raise' },
    { value: 'Dumbbell Goblet Squat' },
    { value: 'Dumbbell Hammer Curl' },
    { value: 'Dumbbell Lateral Raise' },
    { value: 'Dumbbell Lunge' },
    { value: 'Dumbbell Pullover' },
    { value: 'Dumbbell Rear Delt Fly' },
    { value: 'Dumbbell Renegade Row' },
    { value: 'Dumbbell Romanian Deadlift' },
    { value: 'Dumbbell Row' },
    { value: 'Dumbbell Shoulder Press' },
    { value: 'Dumbbell Shrug' },
    { value: 'Dumbbell Squat' },
    { value: 'Dumbbell Step Up' },
    { value: 'Dumbbell Tricep Kickback' },
    { value: 'Dumbbell Upright Row' },
    { value: 'Front Squat' },
    { value: 'Good Morning' },
    { value: 'Hack Squat' },
    { value: 'Incline Bench Press' },
    { value: 'Push Press' },
    { value: 'Romanian Deadlift' },
    { value: 'Skullcrushers' },
    { value: 'Standing Barbell Calf Raise' },
    { value: 'Sumo Deadlift' },
    { value: 'Tricep Extension' },
].map(exercise => ({ label: exercise.value, value: exercise.value }));
